image: microsoft/dotnet:2.2-sdk

stages:
    - build
    - test

before_script:
    # Set configuration
    -  cp SpreadShare/appsettings.json.example SpreadShare/appsettings.json
    -  sed -i "s/api_key/${API_READ_KEY}/g" SpreadShare/appsettings.json
    -  sed -i "s/api_secret/${API_READ_SECRET}/g" SpreadShare/appsettings.json

build:
    stage: build
    script:
        - dotnet restore SpreadShare/SpreadShare.csproj
        - dotnet build SpreadShare/SpreadShare.csproj -p:Configuration=Release /warnaserror

test:
    stage: test
    script:
        - dotnet restore SpreadShare.Tests/SpreadShare.Tests.csproj
        - dotnet build SpreadShare.Tests/SpreadShare.Tests.csproj -p:Configuration=Release /warnaserror
        - dotnet test SpreadShare.Tests/SpreadShare.Tests.csproj
