version: '3.4'

services:
  spreadshare:
    image: ${DOCKER_REGISTRY}spreadshare
    build:
      context: SpreadShare
    depends_on:
      - db
    volumes:
      - ./backtesting-output:/app/backtesting-output # Path-based volume
    tty: true
    stdin_open: true

  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql # Named volume
    # Expose for pgAdmin or remote access
    ports:
      - "5432:5432"

volumes:
  postgres-data:
