version: '3.4'

services:
  # zeromq:
  #   build:
  #     context: zeromq
  #     dockerfile: Dockerfile
  #   entrypoint: python
  #   command: -u zeromq.py
  #   depends_on: 
  #     - spreadshare

  spreadshare:
    image: ${DOCKER_REGISTRY}spreadshare
    build:
      context: .
      dockerfile: SpreadShare/Dockerfile
    depends_on:
      - db
    volumes:
      - ./backtesting-output:/app/backtesting-output # Path-based volume
    tty: true
    stdin_open: true

  # datapump:
  #  build:
  #    context: DataPump
  #    dockerfile: Dockerfile
  #  entrypoint: python
  #  command: -u datapump.py
  #  env_file:
  #    - .env
  #  depends_on: 
  #    - db
  #  volumes:
  #    - ./DataPump/input-data:/app/input-data # Path-based volume

  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql # Named volume
    # Expose for pgAdmin or remote access
    ports:
      - "5432:5432"

volumes:
  postgres-data:
