version: '3.4'

services:
  spreadshare:
    image: ${DOCKER_REGISTRY}spreadshare
    build:
      context: .
      dockerfile: SpreadShare/Dockerfile
    depends_on:
      - db
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql:Z

volumes:
  postgres-data:
    external: true
